TRUCKLE_RESUME_FILE="/tmp/truckle-resume-pid-${$}"
CAVE_all_commands_OPTIONS="--resume-file ${TRUCKLE_RESUME_FILE}"
CAVE_RESOLVE_OPTIONS="${CAVE_all_commands_OPTIONS}"
CAVE_RESUME_OPTIONS="${CAVE_all_commands_OPTIONS}"
CAVE_FIX_LINKAGE_OPTIONS="${CAVE_all_commands_OPTIONS}"
CAVE_UNINSTALL_OPTIONS="${CAVE_all_commands_OPTIONS}"
export TRUCKLE_RESUME_FILE CAVE_all_commands_OPTIONS CAVE_RESOLVE_OPTIONS
export CAVE_RESUME_OPTIONS CAVE_FIX_LINKAGE_OPTIONS CAVE_UNINSTALL_OPTIONS
